### ISSUE TITLE
Release 2022-09

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#247] opened 2022-08-29 14:39 UTC
## Stackable release 22.09

Copied from https://github.com/stackabletech/.github-private/blob/main/profile/README.md:

- [x] Release operators that are part of the release (if release is needed)
  - [x]  Set stable operator versions in the `docs/templating_vars.yaml` file before releasing, and back to nightly afterwards
  - [x] Release the actual operator
  - [x] Bump the operators to the new -nightly version
- [x] Integration tests passed
- [x] Update stackablectl/release.yaml to add the new release => https://github.com/stackabletech/release/pull/11
- [x] Create a Changelog including Release Highlights => https://github.com/stackabletech/documentation/pull/268
- [x] https://github.com/stackabletech/documentation/issues/233 => https://github.com/stackabletech/documentation/pull/268
- [x] Bump documentation @fhennig 
  - [x] Update version of main documentation repo (when it is versioned in the future) https://github.com/stackabletech/documentation/issues/269
- [x] Demos updated if required @sbernauer 
- [x] Update the homepage banner (as long as we have it) to point to the new release
- [x] Write a blogpost announcing the new release (optional) Merged: @adwk67 => EN https://github.com/stackabletech/writing/pull/5 & DE https://github.com/stackabletech/writing/pull/7
  - https://stackable.tech/en/2022/09/14/sdp-release-22-09/ & https://stackable.tech/de/2022/09/14/sdp-release-22-09/ (N.B. will be available via the blog list at https://stackable.tech/en/blog/ once wordpress cache has been refreshed)

### stackablectl

Action: bump and test

| stackablectl element | Who | Status |
| :--- | :--- | :--- |
| stack: kafka-druid-superset-s3 | @sbernauer | https://github.com/stackabletech/stackablectl/pull/105 Noticed kafka port names are wrong |
| stack: trino-superset-s3 | @sbernauer  | https://github.com/stackabletech/stackablectl/pull/105  Created https://github.com/stackabletech/trino-operator/pull/277 |
| stack: airflow | @adwk67 | [104](https://github.com/stackabletech/stackablectl/pull/104) Done |
| stack: hdfs-hbase | @adwk67 | [106](https://github.com/stackabletech/stackablectl/pull/106) |
| demo: trino-taxi-data | @sbernauer | https://github.com/stackabletech/stackablectl/pull/105 |
| demo: kafka-druid-earthquake-data | @sbernauer | https://github.com/stackabletech/stackablectl/pull/105 |
| demo: kafka-druid-water-level-data | @sbernauer | https://github.com/stackabletech/stackablectl/pull/105 |
| demo: hbase-hdfs-load-cycling-data | @adwk67 | [106](https://github.com/stackabletech/stackablectl/pull/106) |

### Operators

Action: release (done), test getting started guides, read/test docs and examples (where relevant)

| Operator | Version | Getting started (who/status) | Docs (who/status) | Release blockers | PR |
| :--- | :---:  | :--- | :--- | :--- | :--- |
| commons | 0.3.0 | Does not exist | :heavy_check_mark:  | | [88](https://github.com/stackabletech/commons-operator/pull/88) & [89](https://github.com/stackabletech/commons-operator/pull/89) | 
| secret | 0.5.0 | - | - | | Don't make a release | | 
| opa | 0.10.0 | @adwk67 | @sbernauer/@adwk67 | | [341](https://github.com/stackabletech/opa-operator/pull/341) & [342](https://github.com/stackabletech/opa-operator/pull/342) & [test](https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/opa-operator-it-custom/10/) | 
| zookeeper | 0.11.0 | @adwk67 | @sbernauer/@adwk67 | | [551](https://github.com/stackabletech/zookeeper-operator/pull/551) & [552](https://github.com/stackabletech/zookeeper-operator/pull/552) & [test](https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/12/) | 
| kafka | 0.7.0 | @adwk67 | @sbernauer/@adwk67 | | [464](https://github.com/stackabletech/kafka-operator/pull/464) & [465](https://github.com/stackabletech/kafka-operator/pull/465) | 
| hdfs | 0.5.0 | @adwk67 | @sbernauer/@adwk67 | | [233](https://github.com/stackabletech/hdfs-operator/pull/233) and [234](https://github.com/stackabletech/hdfs-operator/pull/234) | 
| hive | 0.7.0 | @adwk67 | @sbernauer/@adwk67 | [235](https://github.com/stackabletech/hive-operator/issues/235) | [238](https://github.com/stackabletech/hive-operator/pull/238) and [239](https://github.com/stackabletech/hive-operator/pull/239) | 
| hbase | 0.4.0 | @adwk67 | @adwk67  [docs/0.4](https://github.com/stackabletech/hbase-operator/tree/docs/0.4) | | [243](https://github.com/stackabletech/hbase-operator/pull/243) and [244](https://github.com/stackabletech/hbase-operator/pull/244) | 
| nifi | 0.7.0 | @razvan [343](https://github.com/stackabletech/nifi-operator/pull/343) |@razvan [344](https://github.com/stackabletech/nifi-operator/pull/344)| | [338](https://github.com/stackabletech/nifi-operator/pull/338) and [339](https://github.com/stackabletech/nifi-operator/pull/339) | 
| druid | 0.7.0 |@fhennig [299](https://github.com/stackabletech/druid-operator/pull/299) | @fhennig [299](https://github.com/stackabletech/druid-operator/pull/299) | | [296](https://github.com/stackabletech/druid-operator/pull/296) & [297](https://github.com/stackabletech/druid-operator/pull/297) | 
| trino | 0.6.0 | @adwk67| @sbernauer/@adwk67 | [248](https://github.com/stackabletech/trino-operator/issues/248) [269](https://github.com/stackabletech/trino-operator/issues/269) | [275](https://github.com/stackabletech/trino-operator/pull/275) and [276](https://github.com/stackabletech/trino-operator/pull/276) | 
| spark-k8s | 0.5.0 | @razvan [135](https://github.com/stackabletech/spark-k8s-operator/pull/135)| @razvan| | [132](https://github.com/stackabletech/spark-k8s-operator/pull/132) & [133](https://github.com/stackabletech/spark-k8s-operator/pull/133) | 
| airflow | 0.5.0 | @adwk67 [162](https://github.com/stackabletech/airflow-operator/pull/162) | @adwk67 [162](https://github.com/stackabletech/airflow-operator/pull/162) & [163](https://github.com/stackabletech/airflow-operator/pull/163)| | [160](https://github.com/stackabletech/airflow-operator/pull/160) & [161](https://github.com/stackabletech/airflow-operator/pull/161) | 
| superset | 0.6.0 | @fhennig [269](https://github.com/stackabletech/superset-operator/pull/269) | @fhennig [269](https://github.com/stackabletech/superset-operator/pull/269) | | [264](https://github.com/stackabletech/superset-operator/issues/264) | [267](https://github.com/stackabletech/superset-operator/pull/267) and [268](https://github.com/stackabletech/superset-operator/pull/268) |

**Comment by lfrancke** [comment] 2022-09-05 09:38
Could you break down or elaborate "Bump documentation" a bit?

Does that include upgrading references to 2022-06 release to the new one?
I'm asking because I'm building a release checklist and would like to include some details.

- This does not mention demos, do we want or need to update them as well?
- It also doesn't mention stackablectl / release.yaml changes.
- A changelog is missing and we need to update the homepage as well

Are there more things that need to be done?

**Comment by fhennig** [comment] 2022-09-05 09:58
When releasing an operator with the release script, a new docs version will be created too, as a tag. Before releasing the operator, the Operator versions used in the docs should be set to stable versions, i.e. in this file: https://github.com/stackabletech/druid-operator/blob/main/docs/templating_vars.yaml . These versions show up for example here: https://docs.stackable.tech/druid/nightly/getting_started/installation.html . So:

- Set the versions to stable versions
- release the operator (and thus the docs)
- set the versions to the new nightly versions in the main branch, to have the nightly versions in the nightly docs again

**Comment by fhennig** [comment] 2022-09-05 10:01
The main documentation (not the specific operator docs) is not versioned yet, but I've added support for this last week. There's now a script for it. But there is still a bug in how we build the production docs, I haven't gotten around to making a ticket for it yet.

But once this si fixed, releasing a new platform docs version should be very straight-forward

**Comment by maltesander** [comment] 2022-09-05 14:23
Should we bump every operator to the latest operator-rs? E.g. for orphaned resources etc.?

**Comment by lfrancke** [comment] 2022-09-07 13:43
Did you bump operator-rs?
Is this something we should put into a pre-release checklist to bump operator-rs before the feature freeze (when we have it next time)

**Comment by adwk67** [comment] 2022-09-07 13:47
No we didn't, and yes we probably should :) Were a bit late this time round.

**Comment by adwk67** [comment] 2022-09-07 13:47
Where should we add it - [here](https://github.com/stackabletech/.github-private/blob/main/profile/README.md)?

**Comment by lfrancke** [comment] 2022-09-07 13:53
Yes, please

**Comment by adwk67** [comment] 2022-09-07 13:56
> Yes, please

Done

**Comment by sbernauer** [comment] 2022-09-07 14:01
Thinking about it would consider bumping operator-rs a feature (or at least not a bug-fix) (e.g. bumping kube, supported k8s versions, serde_yaml etc.)
Therefore I would not do it during the feature freeze as i fear it may break stuff

**Comment by sbernauer** [comment] 2022-09-07 14:02
Often time operators-rs bumps are breaking and need rework of operator code

**Comment by lfrancke** [comment] 2022-09-07 14:02
Also a good point. Hence my suggestion would be to do it _before_ the feature freeze. When exactly I don't know but at least once during a release cycle to get new features and security stuff etc.

**Comment by sbernauer** [comment] 2022-09-07 14:09
Oh my fault, i just read "the release checklist". Agreed!

**Comment by adwk67** [comment] 2022-09-07 14:13
Have tried to make that a little clearer:

> Bump every operator to the latest operator-rs at some point before the feature freeze (meaning: at least once in the release cycle, and leaving sufficient time for testing etc.)

**Comment by adwk67** [comment] 2022-09-14 10:38
Closing issue as everything has been implemented.

**Closed by adwk67** 2022-09-14 10:38 UTC

**Comment by lfrancke** [comment] 2022-09-15 11:20
Thank you all for the work! This was awesome to see and I'm really happy with the outcome.
