### ISSUE TITLE
taxi demo not creating demo bucket in MinIO S3

### ISSUE THREAD

**Issue by alexmc6** [stackabletech/issues#467] opened 2023-11-29 15:14 UTC
As a new Stackable user I am trying out the demos on my small k8s cluster. This is obviously low priority since it is not a production issue, I am just learning. 

I would like to run **stackablectl demo install trino-taxi-data** and get a working demo. 

Problem 0) 
Can I run this command repeatedly until it works? If not then what is the alternative/workaround?

Problem 1) 
Sometimes I get the error 

```
  ERROR  Go wrapper function go_add_helm_repo encountered an error: error converting JSON to YAML: yaml: control characters are not allowed
    at rust/stackable-cockpit/src/helm.rs:400

```
Trying to Set SNAFU_RAW_ERROR_MESSAGES=1 does not seem to add to this information. It is not clear where to look for logs or get more information. 

Problem 2) 
(happy to create a second issue if these are separate problems)

Job load-ny-taxi-data seems to be failing *sometimes* with the error Bucket `demo` does not exist.
eg from the logs for that job 

```
Added `minio` successfully.
`/tmp/yellow_tripdata_2021-09.parquet` -> `minio/demo/ny-taxi-data/raw/yellow_tripdata_2021-09.parquet`
mc: <ERROR> Failed to copy `/tmp/yellow_tripdata_2021-09.parquet`. Bucket `demo` does not exist.
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

Is the work around to simply create a bucket called "demo" or will that get reinitialised? (I am trying this workaround now)

```
 stackablectl stacklet list
┌──────────┬───────────────┬───────────┬────────────────────────────────────────────────┬─────────────────────────────────┐
│ PRODUCT  ┆ NAME          ┆ NAMESPACE ┆ ENDPOINTS                                      ┆ CONDITIONS                      │
╞══════════╪═══════════════╪═══════════╪════════════════════════════════════════════════╪═════════════════════════════════╡
│ hive     ┆ hive          ┆ default   ┆                                                ┆ Available, Reconciling, Running │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ opa      ┆ opa           ┆ default   ┆                                                ┆ Available, Reconciling, Running │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ superset ┆ superset      ┆ default   ┆ external-superset   http://192.168.1.23:32148  ┆ Available, Reconciling, Running │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ trino    ┆ trino         ┆ default   ┆ coordinator-metrics 192.168.1.75:31416         ┆ Available, Reconciling, Running │
│          ┆               ┆           ┆ coordinator-https   https://192.168.1.75:30614 ┆                                 │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ minio    ┆ minio-console ┆ default   ┆ http                http://192.168.1.74:30223  ┆                                 │
└──────────┴───────────────┴───────────┴────────────────────────────────────────────────┴─────────────────────────────────┘
```

Likewise job create-ny-taxi-data-table-in-trino is failing because the bucket doesn't exist - so there is nothing to point trino at

Please note:

$ stackablectl --version
stackablectl 1.0.0-rc2

Should I downgrade to something that isn't a release candidate?

**Comment by alexmc6** [comment] 2023-11-29 15:18
Manually creating a bucket called "demo" using the MinIO admin web interface means that I am progressing, but I don't know if that is an appropriate workaround.

**Comment by Techassi** [comment] 2023-11-29 15:28
> Problem 1)
> Sometimes I get the error
> 
> ```
>   ERROR  Go wrapper function go_add_helm_repo encountered an error: error converting JSON to YAML: yaml: control characters are not allowed
>     at rust/stackable-cockpit/src/helm.rs:400
> ```
>
> Trying to Set SNAFU_RAW_ERROR_MESSAGES=1 does not seem to add to this information. It is not clear where to look for logs or get more information.

Which `stackablectl` version are you using? This should be fixed by our latest release candidate: [stackablectl-23.11.0-rc4](https://github.com/stackabletech/stackable-cockpit/releases/tag/stackablectl-23.11.0-rc4). A non RC version (23.11.0) of `stackablectl` will release in the upcoming days.

**Comment by sbernauer** [comment] 2023-11-29 15:51
Hi @alexmc6 thanks for reporting this!
The problem is that the first invocation started "helm install minio", but did not complete it successfully (hence the bucket and propably user is missing).
Sadly during the second invocation stackablectl saw "oh, minio is already installed - nothing to do", so the installation was never completed successfully.

To resolve the problem you can "helm uninstall minio" and re-run the command to install minio properly again - please note that this might cause data loss in minio. To be 100% safe I would recommend to get rid of the local Kubernetes (or the namespace) and re-run the demo installation.

Last of: The probably easiest fix it to simple create the bucket via the UI - it will not be recreated or dropped or stuff ;)

**Comment by alexmc6** [comment] 2023-11-30 10:34
Thanks both of you. That is really helpful. If I don't get back to you feel free to close this issue. 

I have manually created the minio S3 bucket "demo" and the system seems to have downloaded over 1Gb of data into it. I seem to have stacklet endpoints for superset and trino (but not hive or opa) so I will investigate the demo further.

**Comment by sbernauer** [comment] 2023-11-30 14:32
Awesome! That sounds fine, as Trino and Superset are exposed outside the Kubernetes cluster using NodePort services.
Hive and OPA have no endpoint shown, as they are considered internal services and are not exposed externally of the Kubernetes cluster.
If you still want to access them you can still port-forward to them using `kubectl port-forward`

As long as the services are show as `Available, Reconciling, Running` as shown below, everything should be running and functional :+1:
```
┌──────────┬──────────┬───────────┬───────────────────────────────────────────────────┬─────────────────────────────────┐
│ PRODUCT  ┆ NAME     ┆ NAMESPACE ┆ ENDPOINTS                                         ┆ CONDITIONS                      │
╞══════════╪══════════╪═══════════╪═══════════════════════════════════════════════════╪═════════════════════════════════╡
│ opa      ┆ opa      ┆ default   ┆                                                   ┆ Available, Reconciling, Running │
```

**Comment by alexmc6** [comment] 2023-12-02 16:05
"Hive and OPA have no endpoint shown, as they are considered internal services and are not exposed externally of the Kubernetes cluster." This is very helpful to know. I think the docs might make that a bit clearer. 

I set up some scripts to kubectl delete almost everything and then reinstall the demo. It seemed to want to latest release 23.11, so I fetched the latest stackablectl and I no longer have this problem. Please close the issue.

**Comment by Techassi** [comment] 2023-12-04 08:45
Closing for now. Feel free to ping us if we should re-open the issue @alexmc6

**Closed by Techassi** 2023-12-04 08:45 UTC

**Comment by sbernauer** [comment] 2023-12-04 09:10
Regarding the service exposition we have the following concepts page: https://docs.stackable.tech/home/stable/concepts/service-exposition

Tho chose on what to expose it up to the individual demo, as our default in the operators is `cluster-internal` to have an safe default. However I think it's a good idea that stackablectl shows something like `<cluster-internal>` in the `stacklet list` command.
