### ISSUE TITLE
Roll out pause functionality across all operators

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#366] opened 2023-03-27 06:59 UTC
Related to https://github.com/stackabletech/issues/issues/72

Roll out pause functionality across all operators (product, not internal) including adjusting documentation, adding a test case and feature tracker entries.

TODO: add a label (either a new one such as "scheduled for release 23.4" or "release-23.4") against the items that should be in the release when issues are created.

Implementation:

- https://github.com/stackabletech/operator-rs/pull/573
- https://github.com/stackabletech/airflow-operator/pull/257
- [ ] Druid
- https://github.com/stackabletech/hbase-operator/pull/336
- https://github.com/stackabletech/hdfs-operator/pull/337
- [ ] Hive
- [ ] Kafka
- [ ] NiFi
- [ ] Spark
- [ ] Superset
- [ ] Trino
- https://github.com/stackabletech/zookeeper-operator/pull/660

**Comment by razvan** [comment] 2023-04-03 09:07
This is a duplicate of https://github.com/stackabletech/issues/issues/72.

**Closed by razvan** 2023-04-03 09:07 UTC
Labels: scheduled-for-23.4
